## Numpy

In [1]:
import numpy as np

### Zadanie 1.

Stwórz losową tablicę 10,000 liczb, następnie do każdego elementu dodaj 1. Następnie napisz dokładnie tę samą funkcję używając `numpy` i jego tablic. Porównaj czas działania swoich rozwiązań.

In [15]:
import random


%timeit random_arr = [x + 1 for x in [random.random() for _ in range(10000)]]


1.59 ms ± 60.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
%timeit np.random.rand(10000) + 1

76.7 µs ± 7.76 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Zadanie 2.

Napisz funkcje obliczajaca $\sin(x) + \cos(x)$ dla kazdego elementu tablicy 10,000 losowych liczb używając pętli oraz używając numpy, porownaj ich szybkość podobnie jak w poprzednim zadaniu.

In [16]:
from math import sin, cos

%timeit [sin(x) + cos(x) for x in [random.random() for _ in range(10000)]]


3.12 ms ± 362 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
%%timeit 
 
X = np.random.rand(10000)
y = np.sin(X) + np.cos(X)

313 µs ± 97.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Zadanie 3.

Napisz wydajniejszą forme następujących funkcji. Dopisz do każdej test potwierdzający szybkość zaproponowanego rozwiązania.

In [20]:
def cube_sum(x):
    """Zwraca sume szescianow elementow"""
    result = 0
    for i in range(len(x)):
        result += x[i] ** 3
    return result

def almost_variance(x):
    """Oblicza 1/n * SUM (x_i - mean(x))^4"""
    m = sum(x) / len(x)
    result = 0
    for i in range(len(x)):
        result += (x[i] - m) ** 4
    result /= len(x)
    return result
    


def numpy_variance(x):
    mean = np.mean(x)
    powers = (x - mean) ** 4
    return np.mean(powers)

   

In [23]:
%timeit almost_variance(np.random.rand(10000))
%timeit numpy_variance(np.random.rand(10000))

7.37 ms ± 147 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
370 µs ± 1.09 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Zadanie 4.

Wykorzystujac `broadcasting` (patrz na rysunek poniżej) stwórz tabliczkę mnożenia tzn. tablice $A$ taka, ze $$A_{ij} = i \cdot j\;\;\;\;\; \forall i,j \in \{1,\dots,10\}$$

Czy potrafisz wykonać to jednym poleceniem, nie używajac przy tym petli/comprehensions?

<img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">

In [68]:
def multiplication_table(K):
    return (np.arange(1,K +1).reshape(K,1)) * (np.arange(1,K +1))

print("Wynik funkcji multiplication:\n", multiplication_table(10))




Wynik funkcji multiplication:
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Zad 5.

Wygeneruj losową tablice `10 x 5`, która będzie reprezentować `10` punktów w `5` wymiarowej przestrzeni. Napisz funkcje, która policzy odleglość euklidesową pomiędzy każdą parą punktów, czy potrafisz zrobić to **bez użycia żadnych pętli/comprehensions**? 

Przypomnienie, dla dwóch wektorów: $x$ i $y$ $$d_{e}(x,y) = \| x - y \|^2_2 = \sum_{i=1}^d (x_i - y_i)^2 $$

In [29]:
random_matrix = np.random.rand(10,5)
print(random_matrix)


[[0.13512376 0.49485484 0.92245231 0.35061188 0.26604448]
 [0.33801412 0.47504148 0.92422627 0.53891892 0.27734904]
 [0.21244861 0.86324532 0.91303293 0.64968092 0.54494233]
 [0.41401028 0.34466146 0.83395041 0.82500356 0.1949027 ]
 [0.88177552 0.22106842 0.93394329 0.45023035 0.59461701]
 [0.75192368 0.88837201 0.46149951 0.00512145 0.15112478]
 [0.5936843  0.46577043 0.81086083 0.06443948 0.39062884]
 [0.10476434 0.36849442 0.87859516 0.72126061 0.47490543]
 [0.19388451 0.49215415 0.43675003 0.14685645 0.66299777]
 [0.75299897 0.22115253 0.48151733 0.324966   0.08069757]]


### Zad 6.

Napisz funkcje do "wybielania" zbioru punktow, tj. aplikowania następującej transformacji (ponownie, zrób to bez użycia pętli etc.)
$$
\mathrm{white}(X)_{ij} = \frac{X_{ij} - \mu_j}{\sigma_j}
$$
gdzie $\mu_j$ to srednia po $j$ej kolumnie, a $\sigma_j$ to odchylenie standardowe po tej kolumnie, np.

$$
\mathrm{white}\left ( \left [ \begin{matrix} 
0& 1\\
2& 3\\
4& 5\\
6& 7\\
8& 9
\end{matrix} \right ] \right ) = 
\left [ \begin{matrix} 
-1.41421356& -1.41421356\\
-0.70710678& -0.70710678\\
0.        &  0.        \\
0.70710678&  0.70710678\\
1.41421356&  1.41421356
\end{matrix} \right ]
$$

W szczególności średnia po poszczególnych kolumnach nowej macierzy powinna wynosić `0` a odchylenie standardowe `1`.

In [38]:
X = np.random.rand(10).reshape(5,2)
print(X)
whiten = (X - np.mean(X,axis=0))/np.std(X,axis=0)
print(whiten)
print(np.mean(whiten, axis=0))
print(np.std(whiten, axis=0))

[[0.7155435  0.1828605 ]
 [0.53712233 0.18447105]
 [0.86740113 0.41296551]
 [0.78429899 0.33659937]
 [0.14657671 0.27357529]]
[[ 0.41143799 -1.07189469]
 [-0.28534214 -1.05376733]
 [ 1.00448073  1.51802847]
 [ 0.6799457   0.65849726]
 [-1.81052228 -0.05086371]]
[-4.44089210e-17 -5.07927034e-16]
[1. 1.]


### Zad 7.

Majac dana tablice dowolnie wymiarowa (dla uproszczenia mozesz przyjac ze jedno lub dwu) oraz liczbe `x` znajdz najblizsza wartosc `x` w `A`, tzn. 

$$
\mathrm{closest}(x, A) = \arg\min_{a\in A}| x - a| 
$$

np. 

$$
\mathrm{closest}(1.5, [1, -4, 3]) = 1
$$

Ponownie, czy potrafisz zrobic to bez petli, etc.?


In [43]:
def closest(x, arr):
    return arr[np.argmin(np.abs(x-arr))]
arr = np.array([4,66,7,2])
closest_item = closest(10,arr)
print(closest_item)

7


### Zad 8.

Zaimplementuj proste liczenie wartosci wielomianu o zadanych wspolczynnikach (analogie `np.poly1d`), czyli funkcje

$$
\mathrm{poly}(x, a) = a_0 + a_1 x + a_2 x^2 + \dots + a_k x^k = \sum_{i=1}^k a_i x^i
$$

Czy potrafisz zrobic to jednolinijkowo bez uzycia petli, etc. (oraz oczywiście `np.poly1d`). 
Może Ci się przydać metoda `cumprod`.

## Obrazki

Do wyświetlania obrazków w notebooku potrzebny będzie `matplotlib`. W PyCharmie można użyć `imshow` z biblioteki `scipy`.

In [58]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [59]:
img = mpimg.imread('images/doggo.jpeg')
plt.imshow(img)

ValueError: Only know how to handle PNG; with Pillow installed, Matplotlib can handle more images

### Zad 9.

Napisz funckje do przetwarzania obrazu do skali szarości wg wzoru:

$$ 0.2126 \times R + 0.7152 \times  G + 0.0722 \times B $$

### Zadanie 10.

Wyłącznie za pomocą metod numpy napisz kod do interpolacji liniowej pomiędzy parą punktów (dowolnej wymiarowości) wg wzoru:

$$ x_i = \lambda x_1 + (1 - \lambda) x_2$$

Kod powinien od razu generować interpolacje dla wielu wartości $\lambda$, np dla 10 różnych $\lambda \in \{0, 0.1, 0.2, \dots, 1\}$